name: Update Content

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *' # Runs at 8 AM UTC every day

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Aggregator Script
        run: python aggregator.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if [ -n "" ]; then
            git commit -m "Automated content update"
            git push
          else
            echo "No changes to commit."
          fi
